package com.hospital.controller.command;

public enum CommandName {
    LOGIN,
    REGISTRATION,
    LOGOUT,
    ADDACCOUNT,
    GOTOINDEXPAGE,
    GOTOMAINSTAFFPAGE,
    GOTOMAINPATIENTPAGE,
    ADDADDITIONALINFOPAGE,
    CHANGELOCALE,
    GOTODOCTORSPATIENTSPAGE,
    GOTOFREEPATIENTSPAGE,
    ADDPATIENTSTODOCTOR,
    GOTOPROFILEPAGE,
    GOTOADDAPPOINTMENTPAGE,
    GOTOADDAPPOINTMENTNEXTPAGE,
    ADDAPPOINTMENT,
    GOTOSTAFFAPPOINTMENTLISTPAGE,
    GOTOPATIENTAPPOINTMENTLISTPAGE,
    UPDATEAPPOINTMENTSTATUS
}
